# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

# All lanes for the iOS app 
platform :ios do
  desc "Signs the iOS application with the proper certificate and installs proper provisioning profiles"
  lane :signing do
    # add actions here: https://docs.fastlane.tools/actions
  end

  desc "Building WTHR ipa file" 
  lane :build do 
    # Build iOS application ipa file
    signing
    gym(
	scheme: "WTHR",
	workspace: "WTHR.xcworkspace",
	export_method: "development",
	configuration: "Debug",
	clean: true,
	output_directory: "build",
	output_name: "wthr"
    )
  end

  desc "Release IPA to firebase"
  lane :release do
    # release app to app store 
  end
end
